// lib/config/yolo_labels_config.dart
//
// YOLO model labels configuration.
// Labels must strictly match frontend-app/assets/models/label.txt and backend
// ref_standard_ingredients (backend data.sql) for the same 83 classes.
// Order: 0='Apple', 1='Apricot', ..., 82='Mushroom'
//
// Model: nc: 83, names from label.txt

/// List of all recognizable ingredient labels from the YOLO model
/// This list must match the model's data.yaml configuration exactly
const List<String> yoloLabels = [
  'Apple',
  'Apricot',
  'Asparagus',
  'Avocado',
  'Banana',
  'Beef',
  'Beetroot',
  'Blackberry',
  'Blueberry',
  'Bok-Choy',
  'Broccoli',
  'Cabbage',
  'Cantaloupe',
  'Capsicum',
  'Carrot',
  'Cauliflower',
  'Celery',
  'Cherry',
  'Chicken-Breast',
  'Chicken-Leg',
  'Chicken-Quater',
  'Chicken-Thigh',
  'Chicken-Whole',
  'Chicken-Wing',
  'Coconut',
  'Corn',
  'Courgette',
  'Crab',
  'Cucumber',
  'Dragon-Fruit',
  'Egg',
  'Eggplant',
  'Garlic',
  'Ginger',
  'Grape',
  'Green-Pepper',
  'Guava',
  'Kale',
  'Kiwifruit',
  'Lamb',
  'Leek',
  'Lemon',
  'Lettuce',
  'Lime',
  'Longan',
  'Lychee',
  'Mandarin',
  'Mango',
  'Mussels',
  'Nectarine',
  'Onion',
  'Orange',
  'Papaya',
  'Parsnip',
  'Peach',
  'Pear',
  'Persimmon',
  'Pineapple',
  'Plum',
  'Pomegranate',
  'Pork',
  'Potato',
  'Pumpkin',
  'Radish',
  'Raspberry',
  'Red-Pepper',
  'Salmon',
  'Sausage',
  'Scallop',
  'Sea-Bass',
  'Shiitake',
  'Shrimp',
  'Snapper',
  'Spinach',
  'Spring-Onion',
  'Squid',
  'Strawberry',
  'Swede',
  'Sweet-Potato',
  'Tofu',
  'Tomato',
  'Watermelon',
  'Mushroom',
];

/// Total number of classes in the YOLO model
const int yoloClassCount = 83;
