// lib/config/yolo_labels_config.dart
//
// YOLO model labels configuration
// Labels must strictly match the model's data.yaml configuration (96 classes)
// Order: 0='Apple', 1='Apricot', 2='Asparagus', ..., 95='White-Rice'
//
// Model configuration reference:
// nc: 96
// names: ['Apple', 'Apricot', 'Asparagus', ..., 'White-Rice']

/// List of all recognizable ingredient labels from the YOLO model
/// This list must match the model's data.yaml configuration exactly
const List<String> yoloLabels = [
  'Apple',
  'Apricot',
  'Asparagus',
  'Avocado',
  'Bagel',
  'Banana',
  'Beef',
  'Beetroot',
  'Blackberry',
  'Blueberry',
  'Bok-Choy',
  'Broccoli',
  'Brown-rice',
  'Butter',
  'Cabbage',
  'Cantaloupe',
  'Capsicum',
  'Carrot',
  'Cauliflower',
  'Celery',
  'Cherry',
  'Chicken-Breast',
  'Chicken-Leg',
  'Chicken-Quater',
  'Chicken-Thigh',
  'Chicken-Whole',
  'Chicken-Wing',
  'Chickpea',
  'Coconut',
  'Corn',
  'Zucchini',
  'Crab',
  'Cucumber',
  'Dragon-Fruit',
  'Eggplant',
  'Eggs',
  'Garlic',
  'Ginger',
  'Grape',
  'Green-Pepper',
  'Guava',
  'Kale',
  'Kiwifruit',
  'Lamb',
  'Leek',
  'Lemon',
  'Lentil',
  'Lettuce',
  'Lime',
  'Longan',
  'Lychee',
  'Mandarin',
  'Mango',
  'Milk',
  'Millet',
  'Minced-Meat',
  'Mushroom',
  'Mussels',
  'Nectarine',
  'Oats',
  'Onion',
  'Orange',
  'Papaya',
  'Parsnip',
  'Pasta',
  'Peach',
  'Pear',
  'Persimmon',
  'Pineapple',
  'Plum',
  'Pomegranate',
  'Pork',
  'Potato',
  'Pumpkin',
  'Radish',
  'Raspberry',
  'Red-Pepper',
  'Salmon',
  'Sausage',
  'Scallop',
  'Sea-Bass',
  'Sesame-Seeds',
  'Shiitake',
  'Shrimp',
  'Snapper',
  'Spinach',
  'Spring-Onion',
  'Squid',
  'Strawberry',
  'Swede',
  'Sweet-Potato',
  'Tofu',
  'Tomato',
  'Tuna',
  'Watermelon',
  'White-Rice',
];

/// Total number of classes in the YOLO model
const int yoloClassCount = 96;
