spring:
  datasource:
    username: postgres
    password: mysecretpassword
    url: jdbc:postgresql://127.0.0.1:5432/sous_chef?currentSchema=sous_chef_cms&useUnicode=true&characterEncoding=utf8
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: AUTO

server:
  port: 7000