version: '3.8'

services:
  #这是我们要跑 Java 代码的容器（开发环境）
  app:
    # 使用微软官方为 VS Code 优化的 Java 17 镜像
    image: mcr.microsoft.com/devcontainers/java:1-17-bullseye
    volumes:
      # 把你的项目代码挂载到容器里
      - ../:/workspaces/backend-java:cached
    
    # 让容器一直运行，不要退出
    command: sleep infinity

    # 这里的关键：设置网络，让它能找到旁边的数据库
    # (只要和根目录的 compose 文件一起启动，它们就在同一个网络里)
    
  # 这里不需要再写数据库了，因为我们会引用根目录的那个文件