// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SousChefBackend.Data;

#nullable disable

namespace SousChefBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251203053324_FinalFusion")]
    partial class FinalFusion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SousChefBackend.Models.AiGenerationSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CookersSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DifficultyTarget")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DishCount")
                        .HasColumnType("integer");

                    b.Property<string>("InventorySnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KitchenId")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxCookingTimeMin")
                        .HasColumnType("integer");

                    b.Property<string>("PreferencesSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Servings")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetMaxCalories")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetMinCalories")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AiGenerationSessions");
                });

            modelBuilder.Entity("SousChefBackend.Models.GeneratedRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CookingTimeMin")
                        .HasColumnType("integer");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IngredientsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Servings")
                        .HasColumnType("integer");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StepsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalCaloriesEstimate")
                        .HasColumnType("double precision");

                    b.Property<string>("UsedCookwaresJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GeneratedRecipes");
                });

            modelBuilder.Entity("SousChefBackend.Models.GeneratedRecipeOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AiGenerationSessionId")
                        .HasColumnType("integer");

                    b.Property<int>("CookingTime")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IngredientsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSaved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.Property<int>("Servings")
                        .HasColumnType("integer");

                    b.Property<string>("StepsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalCalories")
                        .HasColumnType("double precision");

                    b.Property<string>("UsedCookwaresJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AiGenerationSessionId");

                    b.ToTable("GeneratedRecipeOptions");
                });

            modelBuilder.Entity("SousChefBackend.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KitchenId")
                        .HasColumnType("integer");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<int>("StandardIngredientId")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KitchenId");

                    b.HasIndex("StandardIngredientId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("SousChefBackend.Models.Kitchen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Kitchens");
                });

            modelBuilder.Entity("SousChefBackend.Models.MyCookware", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<int>("KitchenId")
                        .HasColumnType("integer");

                    b.Property<int>("StandardCookwareId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KitchenId");

                    b.HasIndex("StandardCookwareId");

                    b.ToTable("MyCookwares");
                });

            modelBuilder.Entity("SousChefBackend.Models.MySeasoning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<int>("KitchenId")
                        .HasColumnType("integer");

                    b.Property<int>("StandardSeasoningId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KitchenId");

                    b.HasIndex("StandardSeasoningId");

                    b.ToTable("MySeasonings");
                });

            modelBuilder.Entity("SousChefBackend.Models.StandardCookware", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StandardCookwares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AiCode = "stove",
                            Name = "Stove Top"
                        },
                        new
                        {
                            Id = 2,
                            AiCode = "oven",
                            Name = "Oven"
                        },
                        new
                        {
                            Id = 3,
                            AiCode = "microwave",
                            Name = "Microwave"
                        },
                        new
                        {
                            Id = 4,
                            AiCode = "air_fryer",
                            Name = "Air Fryer"
                        },
                        new
                        {
                            Id = 5,
                            AiCode = "rice_cooker",
                            Name = "Rice Cooker"
                        },
                        new
                        {
                            Id = 6,
                            AiCode = "pressure_cooker",
                            Name = "Pressure Cooker"
                        },
                        new
                        {
                            Id = 7,
                            AiCode = "blender",
                            Name = "Blender"
                        });
                });

            modelBuilder.Entity("SousChefBackend.Models.StandardIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StandardIngredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseUnit = "g",
                            Category = "Meat",
                            ImageUrl = "",
                            Name = "Beef Steak"
                        },
                        new
                        {
                            Id = 2,
                            BaseUnit = "g",
                            Category = "Meat",
                            ImageUrl = "",
                            Name = "Chicken Breast"
                        },
                        new
                        {
                            Id = 3,
                            BaseUnit = "g",
                            Category = "Meat",
                            ImageUrl = "",
                            Name = "Pork Belly"
                        },
                        new
                        {
                            Id = 4,
                            BaseUnit = "piece",
                            Category = "Dairy",
                            ImageUrl = "",
                            Name = "Egg"
                        },
                        new
                        {
                            Id = 5,
                            BaseUnit = "g",
                            Category = "Vegetable",
                            ImageUrl = "",
                            Name = "Tomato"
                        },
                        new
                        {
                            Id = 6,
                            BaseUnit = "g",
                            Category = "Vegetable",
                            ImageUrl = "",
                            Name = "Potato"
                        },
                        new
                        {
                            Id = 7,
                            BaseUnit = "g",
                            Category = "Vegetable",
                            ImageUrl = "",
                            Name = "Onion"
                        },
                        new
                        {
                            Id = 8,
                            BaseUnit = "g",
                            Category = "Grains",
                            ImageUrl = "",
                            Name = "Rice"
                        },
                        new
                        {
                            Id = 9,
                            BaseUnit = "g",
                            Category = "Nuts",
                            ImageUrl = "",
                            Name = "Peanut"
                        },
                        new
                        {
                            Id = 10,
                            BaseUnit = "g",
                            Category = "Vegetable",
                            ImageUrl = "",
                            Name = "Carrot"
                        },
                        new
                        {
                            Id = 11,
                            BaseUnit = "ml",
                            Category = "Dairy",
                            ImageUrl = "",
                            Name = "Milk"
                        },
                        new
                        {
                            Id = 12,
                            BaseUnit = "g",
                            Category = "Dairy",
                            ImageUrl = "",
                            Name = "Cheese"
                        });
                });

            modelBuilder.Entity("SousChefBackend.Models.StandardSeasoning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StandardSeasonings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AiCode = "salt",
                            Name = "Salt"
                        },
                        new
                        {
                            Id = 2,
                            AiCode = "sugar",
                            Name = "Sugar"
                        },
                        new
                        {
                            Id = 3,
                            AiCode = "soy_sauce",
                            Name = "Soy Sauce"
                        },
                        new
                        {
                            Id = 4,
                            AiCode = "black_pepper",
                            Name = "Black Pepper"
                        },
                        new
                        {
                            Id = 5,
                            AiCode = "oil",
                            Name = "Olive Oil"
                        },
                        new
                        {
                            Id = 6,
                            AiCode = "vinegar",
                            Name = "Vinegar"
                        },
                        new
                        {
                            Id = 7,
                            AiCode = "chili_powder",
                            Name = "Chili Powder"
                        },
                        new
                        {
                            Id = 8,
                            AiCode = "garlic_powder",
                            Name = "Garlic Powder"
                        });
                });

            modelBuilder.Entity("SousChefBackend.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<int?>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<int?>("Height")
                        .HasColumnType("integer")
                        .HasColumnName("height");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer")
                        .HasColumnName("weight");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserAllergy", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Allergy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("allergy");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_allergies");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserPreference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("PreferenceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("preference_type");

                    b.Property<string>("PreferenceValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("preference_value");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_preferences");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserTaboo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Taboo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("taboo");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_taboos");
                });

            modelBuilder.Entity("SousChefBackend.Models.GeneratedRecipeOption", b =>
                {
                    b.HasOne("SousChefBackend.Models.AiGenerationSession", null)
                        .WithMany("GeneratedOptions")
                        .HasForeignKey("AiGenerationSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SousChefBackend.Models.InventoryItem", b =>
                {
                    b.HasOne("SousChefBackend.Models.Kitchen", null)
                        .WithMany("InventoryItems")
                        .HasForeignKey("KitchenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SousChefBackend.Models.StandardIngredient", "StandardIngredient")
                        .WithMany()
                        .HasForeignKey("StandardIngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StandardIngredient");
                });

            modelBuilder.Entity("SousChefBackend.Models.Kitchen", b =>
                {
                    b.HasOne("SousChefBackend.Models.User", "User")
                        .WithOne("Kitchen")
                        .HasForeignKey("SousChefBackend.Models.Kitchen", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SousChefBackend.Models.MyCookware", b =>
                {
                    b.HasOne("SousChefBackend.Models.Kitchen", null)
                        .WithMany("MyCookwares")
                        .HasForeignKey("KitchenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SousChefBackend.Models.StandardCookware", "StandardCookware")
                        .WithMany()
                        .HasForeignKey("StandardCookwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StandardCookware");
                });

            modelBuilder.Entity("SousChefBackend.Models.MySeasoning", b =>
                {
                    b.HasOne("SousChefBackend.Models.Kitchen", null)
                        .WithMany("MySeasonings")
                        .HasForeignKey("KitchenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SousChefBackend.Models.StandardSeasoning", "StandardSeasoning")
                        .WithMany()
                        .HasForeignKey("StandardSeasoningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StandardSeasoning");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserAllergy", b =>
                {
                    b.HasOne("SousChefBackend.Models.User", "User")
                        .WithMany("Allergies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserPreference", b =>
                {
                    b.HasOne("SousChefBackend.Models.User", "User")
                        .WithMany("Preferences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserTaboo", b =>
                {
                    b.HasOne("SousChefBackend.Models.User", "User")
                        .WithMany("Taboos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SousChefBackend.Models.AiGenerationSession", b =>
                {
                    b.Navigation("GeneratedOptions");
                });

            modelBuilder.Entity("SousChefBackend.Models.Kitchen", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("MyCookwares");

                    b.Navigation("MySeasonings");
                });

            modelBuilder.Entity("SousChefBackend.Models.User", b =>
                {
                    b.Navigation("Allergies");

                    b.Navigation("Kitchen");

                    b.Navigation("Preferences");

                    b.Navigation("Taboos");
                });
#pragma warning restore 612, 618
        }
    }
}
