// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SousChefBackend.Data;

#nullable disable

namespace SousChefBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251203012616_AddMissingAiFields")]
    partial class AddMissingAiFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SousChefBackend.Models.AiGenerationSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CookersSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DifficultyTarget")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DishCount")
                        .HasColumnType("integer");

                    b.Property<string>("InventorySnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("KitchenId")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxCookingTimeMin")
                        .HasColumnType("integer");

                    b.Property<string>("PreferencesSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Servings")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetMaxCalories")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetMinCalories")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AiGenerationSessions");
                });

            modelBuilder.Entity("SousChefBackend.Models.GeneratedRecipeOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AiGenerationSessionId")
                        .HasColumnType("integer");

                    b.Property<int>("CookingTime")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IngredientsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSaved")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.Property<string>("StepsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalCalories")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AiGenerationSessionId");

                    b.ToTable("GeneratedRecipeOptions");
                });

            modelBuilder.Entity("SousChefBackend.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KitchenId")
                        .HasColumnType("integer");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<int>("StandardIngredientId")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KitchenId");

                    b.HasIndex("StandardIngredientId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("SousChefBackend.Models.Kitchen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Kitchens");
                });

            modelBuilder.Entity("SousChefBackend.Models.MyCookware", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<int>("KitchenId")
                        .HasColumnType("integer");

                    b.Property<int>("StandardCookwareId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KitchenId");

                    b.HasIndex("StandardCookwareId");

                    b.ToTable("MyCookwares");
                });

            modelBuilder.Entity("SousChefBackend.Models.MySeasoning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<int>("KitchenId")
                        .HasColumnType("integer");

                    b.Property<int>("StandardSeasoningId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KitchenId");

                    b.HasIndex("StandardSeasoningId");

                    b.ToTable("MySeasonings");
                });

            modelBuilder.Entity("SousChefBackend.Models.StandardCookware", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StandardCookwares");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AiCode = "stove",
                            Name = "Stove Top"
                        },
                        new
                        {
                            Id = 2,
                            AiCode = "oven",
                            Name = "Oven"
                        },
                        new
                        {
                            Id = 3,
                            AiCode = "microwave",
                            Name = "Microwave"
                        },
                        new
                        {
                            Id = 4,
                            AiCode = "air_fryer",
                            Name = "Air Fryer"
                        },
                        new
                        {
                            Id = 5,
                            AiCode = "rice_cooker",
                            Name = "Rice Cooker"
                        });
                });

            modelBuilder.Entity("SousChefBackend.Models.StandardCuisine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StandardCuisines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AiCode = "chinese",
                            Name = "Chinese"
                        },
                        new
                        {
                            Id = 2,
                            AiCode = "italian",
                            Name = "Italian"
                        },
                        new
                        {
                            Id = 3,
                            AiCode = "japanese",
                            Name = "Japanese"
                        },
                        new
                        {
                            Id = 4,
                            AiCode = "mexican",
                            Name = "Mexican"
                        },
                        new
                        {
                            Id = 5,
                            AiCode = "western",
                            Name = "Western"
                        });
                });

            modelBuilder.Entity("SousChefBackend.Models.StandardIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StandardIngredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseUnit = "g",
                            Category = "Meat",
                            ImageUrl = "",
                            Name = "Beef Steak"
                        },
                        new
                        {
                            Id = 2,
                            BaseUnit = "g",
                            Category = "Meat",
                            ImageUrl = "",
                            Name = "Chicken Breast"
                        },
                        new
                        {
                            Id = 3,
                            BaseUnit = "g",
                            Category = "Meat",
                            ImageUrl = "",
                            Name = "Pork Belly"
                        },
                        new
                        {
                            Id = 4,
                            BaseUnit = "piece",
                            Category = "Dairy",
                            ImageUrl = "",
                            Name = "Egg"
                        },
                        new
                        {
                            Id = 5,
                            BaseUnit = "g",
                            Category = "Vegetable",
                            ImageUrl = "",
                            Name = "Tomato"
                        },
                        new
                        {
                            Id = 6,
                            BaseUnit = "g",
                            Category = "Vegetable",
                            ImageUrl = "",
                            Name = "Potato"
                        },
                        new
                        {
                            Id = 7,
                            BaseUnit = "g",
                            Category = "Vegetable",
                            ImageUrl = "",
                            Name = "Onion"
                        },
                        new
                        {
                            Id = 8,
                            BaseUnit = "g",
                            Category = "Grains",
                            ImageUrl = "",
                            Name = "Rice"
                        },
                        new
                        {
                            Id = 9,
                            BaseUnit = "g",
                            Category = "Nuts",
                            ImageUrl = "",
                            Name = "Peanut"
                        });
                });

            modelBuilder.Entity("SousChefBackend.Models.StandardSeasoning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StandardSeasonings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AiCode = "salt",
                            Name = "Salt"
                        },
                        new
                        {
                            Id = 2,
                            AiCode = "sugar",
                            Name = "Sugar"
                        },
                        new
                        {
                            Id = 3,
                            AiCode = "soy_sauce",
                            Name = "Soy Sauce"
                        },
                        new
                        {
                            Id = 4,
                            AiCode = "black_pepper",
                            Name = "Black Pepper"
                        },
                        new
                        {
                            Id = 5,
                            AiCode = "oil",
                            Name = "Olive Oil"
                        },
                        new
                        {
                            Id = 6,
                            AiCode = "chili_powder",
                            Name = "Chili Powder"
                        });
                });

            modelBuilder.Entity("SousChefBackend.Models.StandardTaste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StandardTastes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AiCode = "spicy",
                            Name = "Spicy"
                        },
                        new
                        {
                            Id = 2,
                            AiCode = "sweet",
                            Name = "Sweet"
                        },
                        new
                        {
                            Id = 3,
                            AiCode = "sour",
                            Name = "Sour"
                        },
                        new
                        {
                            Id = 4,
                            AiCode = "salty",
                            Name = "Salty"
                        },
                        new
                        {
                            Id = 5,
                            AiCode = "light",
                            Name = "Light"
                        });
                });

            modelBuilder.Entity("SousChefBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserAllergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("StandardIngredientId")
                        .HasColumnType("integer");

                    b.Property<int>("UserPreferenceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StandardIngredientId");

                    b.HasIndex("UserPreferenceId");

                    b.ToTable("UserAllergies");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserCuisinePref", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("StandardCuisineId")
                        .HasColumnType("integer");

                    b.Property<int>("UserPreferenceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StandardCuisineId");

                    b.HasIndex("UserPreferenceId");

                    b.ToTable("UserCuisinePrefs");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaxCalories")
                        .HasColumnType("integer");

                    b.Property<int?>("MinCalories")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserTaboo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("StandardIngredientId")
                        .HasColumnType("integer");

                    b.Property<int>("UserPreferenceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StandardIngredientId");

                    b.HasIndex("UserPreferenceId");

                    b.ToTable("UserTaboos");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserTastePref", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("StandardTasteId")
                        .HasColumnType("integer");

                    b.Property<int>("UserPreferenceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StandardTasteId");

                    b.HasIndex("UserPreferenceId");

                    b.ToTable("UserTastePrefs");
                });

            modelBuilder.Entity("SousChefBackend.Models.GeneratedRecipeOption", b =>
                {
                    b.HasOne("SousChefBackend.Models.AiGenerationSession", null)
                        .WithMany("GeneratedOptions")
                        .HasForeignKey("AiGenerationSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SousChefBackend.Models.InventoryItem", b =>
                {
                    b.HasOne("SousChefBackend.Models.Kitchen", null)
                        .WithMany("InventoryItems")
                        .HasForeignKey("KitchenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SousChefBackend.Models.StandardIngredient", "StandardIngredient")
                        .WithMany()
                        .HasForeignKey("StandardIngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StandardIngredient");
                });

            modelBuilder.Entity("SousChefBackend.Models.MyCookware", b =>
                {
                    b.HasOne("SousChefBackend.Models.Kitchen", null)
                        .WithMany("MyCookwares")
                        .HasForeignKey("KitchenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SousChefBackend.Models.StandardCookware", "StandardCookware")
                        .WithMany()
                        .HasForeignKey("StandardCookwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StandardCookware");
                });

            modelBuilder.Entity("SousChefBackend.Models.MySeasoning", b =>
                {
                    b.HasOne("SousChefBackend.Models.Kitchen", null)
                        .WithMany("MySeasonings")
                        .HasForeignKey("KitchenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SousChefBackend.Models.StandardSeasoning", "StandardSeasoning")
                        .WithMany()
                        .HasForeignKey("StandardSeasoningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StandardSeasoning");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserAllergy", b =>
                {
                    b.HasOne("SousChefBackend.Models.StandardIngredient", "StandardIngredient")
                        .WithMany()
                        .HasForeignKey("StandardIngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SousChefBackend.Models.UserPreference", null)
                        .WithMany("Allergies")
                        .HasForeignKey("UserPreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StandardIngredient");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserCuisinePref", b =>
                {
                    b.HasOne("SousChefBackend.Models.StandardCuisine", "StandardCuisine")
                        .WithMany()
                        .HasForeignKey("StandardCuisineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SousChefBackend.Models.UserPreference", null)
                        .WithMany("CuisinePrefs")
                        .HasForeignKey("UserPreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StandardCuisine");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserTaboo", b =>
                {
                    b.HasOne("SousChefBackend.Models.StandardIngredient", "StandardIngredient")
                        .WithMany()
                        .HasForeignKey("StandardIngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SousChefBackend.Models.UserPreference", null)
                        .WithMany("Taboos")
                        .HasForeignKey("UserPreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StandardIngredient");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserTastePref", b =>
                {
                    b.HasOne("SousChefBackend.Models.StandardTaste", "StandardTaste")
                        .WithMany()
                        .HasForeignKey("StandardTasteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SousChefBackend.Models.UserPreference", null)
                        .WithMany("TastePrefs")
                        .HasForeignKey("UserPreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StandardTaste");
                });

            modelBuilder.Entity("SousChefBackend.Models.AiGenerationSession", b =>
                {
                    b.Navigation("GeneratedOptions");
                });

            modelBuilder.Entity("SousChefBackend.Models.Kitchen", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("MyCookwares");

                    b.Navigation("MySeasonings");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserPreference", b =>
                {
                    b.Navigation("Allergies");

                    b.Navigation("CuisinePrefs");

                    b.Navigation("Taboos");

                    b.Navigation("TastePrefs");
                });
#pragma warning restore 612, 618
        }
    }
}
