// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SousChefBackend.Data;

#nullable disable

namespace SousChefBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251202044511_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SousChefBackend.Models.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KitchenId")
                        .HasColumnType("integer");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<int>("StandardIngredientId")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KitchenId");

                    b.HasIndex("StandardIngredientId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("SousChefBackend.Models.Kitchen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Kitchens");
                });

            modelBuilder.Entity("SousChefBackend.Models.MyCookware", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<int>("KitchenId")
                        .HasColumnType("integer");

                    b.Property<int>("StandardCookwareId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KitchenId");

                    b.HasIndex("StandardCookwareId");

                    b.ToTable("MyCookwares");
                });

            modelBuilder.Entity("SousChefBackend.Models.MySeasoning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<int>("KitchenId")
                        .HasColumnType("integer");

                    b.Property<int>("StandardSeasoningId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KitchenId");

                    b.HasIndex("StandardSeasoningId");

                    b.ToTable("MySeasonings");
                });

            modelBuilder.Entity("SousChefBackend.Models.StandardCookware", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StandardCookwares");
                });

            modelBuilder.Entity("SousChefBackend.Models.StandardCuisine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StandardCuisine");
                });

            modelBuilder.Entity("SousChefBackend.Models.StandardIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StandardIngredients");
                });

            modelBuilder.Entity("SousChefBackend.Models.StandardSeasoning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StandardSeasonings");
                });

            modelBuilder.Entity("SousChefBackend.Models.StandardTaste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StandardTaste");
                });

            modelBuilder.Entity("SousChefBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserAllergy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("StandardIngredientId")
                        .HasColumnType("integer");

                    b.Property<int>("UserPreferenceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StandardIngredientId");

                    b.HasIndex("UserPreferenceId");

                    b.ToTable("UserAllergy");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserCuisinePref", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("StandardCuisineId")
                        .HasColumnType("integer");

                    b.Property<int>("UserPreferenceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StandardCuisineId");

                    b.HasIndex("UserPreferenceId");

                    b.ToTable("UserCuisinePref");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MaxCalories")
                        .HasColumnType("integer");

                    b.Property<int?>("MinCalories")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserPreferences");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserTaboo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("StandardIngredientId")
                        .HasColumnType("integer");

                    b.Property<int>("UserPreferenceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StandardIngredientId");

                    b.HasIndex("UserPreferenceId");

                    b.ToTable("UserTaboo");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserTastePref", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("StandardTasteId")
                        .HasColumnType("integer");

                    b.Property<int>("UserPreferenceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StandardTasteId");

                    b.HasIndex("UserPreferenceId");

                    b.ToTable("UserTastePref");
                });

            modelBuilder.Entity("SousChefBackend.Models.InventoryItem", b =>
                {
                    b.HasOne("SousChefBackend.Models.Kitchen", null)
                        .WithMany("InventoryItems")
                        .HasForeignKey("KitchenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SousChefBackend.Models.StandardIngredient", "StandardIngredient")
                        .WithMany()
                        .HasForeignKey("StandardIngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StandardIngredient");
                });

            modelBuilder.Entity("SousChefBackend.Models.MyCookware", b =>
                {
                    b.HasOne("SousChefBackend.Models.Kitchen", null)
                        .WithMany("MyCookwares")
                        .HasForeignKey("KitchenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SousChefBackend.Models.StandardCookware", "StandardCookware")
                        .WithMany()
                        .HasForeignKey("StandardCookwareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StandardCookware");
                });

            modelBuilder.Entity("SousChefBackend.Models.MySeasoning", b =>
                {
                    b.HasOne("SousChefBackend.Models.Kitchen", null)
                        .WithMany("MySeasonings")
                        .HasForeignKey("KitchenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SousChefBackend.Models.StandardSeasoning", "StandardSeasoning")
                        .WithMany()
                        .HasForeignKey("StandardSeasoningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StandardSeasoning");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserAllergy", b =>
                {
                    b.HasOne("SousChefBackend.Models.StandardIngredient", "StandardIngredient")
                        .WithMany()
                        .HasForeignKey("StandardIngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SousChefBackend.Models.UserPreference", null)
                        .WithMany("Allergies")
                        .HasForeignKey("UserPreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StandardIngredient");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserCuisinePref", b =>
                {
                    b.HasOne("SousChefBackend.Models.StandardCuisine", "StandardCuisine")
                        .WithMany()
                        .HasForeignKey("StandardCuisineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SousChefBackend.Models.UserPreference", null)
                        .WithMany("CuisinePrefs")
                        .HasForeignKey("UserPreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StandardCuisine");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserTaboo", b =>
                {
                    b.HasOne("SousChefBackend.Models.StandardIngredient", "StandardIngredient")
                        .WithMany()
                        .HasForeignKey("StandardIngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SousChefBackend.Models.UserPreference", null)
                        .WithMany("Taboos")
                        .HasForeignKey("UserPreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StandardIngredient");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserTastePref", b =>
                {
                    b.HasOne("SousChefBackend.Models.StandardTaste", "StandardTaste")
                        .WithMany()
                        .HasForeignKey("StandardTasteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SousChefBackend.Models.UserPreference", null)
                        .WithMany("TastePrefs")
                        .HasForeignKey("UserPreferenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StandardTaste");
                });

            modelBuilder.Entity("SousChefBackend.Models.Kitchen", b =>
                {
                    b.Navigation("InventoryItems");

                    b.Navigation("MyCookwares");

                    b.Navigation("MySeasonings");
                });

            modelBuilder.Entity("SousChefBackend.Models.UserPreference", b =>
                {
                    b.Navigation("Allergies");

                    b.Navigation("CuisinePrefs");

                    b.Navigation("Taboos");

                    b.Navigation("TastePrefs");
                });
#pragma warning restore 612, 618
        }
    }
}
